### ISSUE TITLE
Make column names singular

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-2-devel#78]
Generalization of the 
- #15 

Looking at column names we do not have consistency.

<details>
<summary>grep '^[a-z]' src/schema/objects/columns.yaml | grep -v __ </summary> 

```shell
abbreviation:
age:
cardiac:
channel:
color:
component:
detector_type:
derived_from:
desc_id:
description:
dimension:
duration:
filename:
handedness:
hemisphere:
high_cutoff:
hplc_recovery_fractions:
impedance:
index:
low_cutoff:
manufacturer:
mapping:
material:
metabolite_parent_fraction:
metabolite_polar_fraction:
notch:
onset:
pathology:
participant_id:
plasma_radioactivity:
reference_frame:
respiratory:
response_time:
sample_id:
sample_type:
sampling_frequency:
session_id:
sex:
short_channel:
size:
software_filters:
species:
status:
status_description:
stim_file:
strain:
strain_rrid:
time:
trial_type:
trigger:
units:
volume_type:
wavelength_nominal:
wavelength_actual:
wavelength_emission_actual:
whole_blood_radioactivity:
x:
y:
z:
template_x:
template_y:
template_z:
```
</details>

<details>
<summary>Dirty list: grep '^[a-z]' src/schema/objects/columns.yaml | grep -v __ | grep 's:'</summary> 

```shell
handedness:
hplc_recovery_fractions:
software_filters:
species:
status:
units:
```
</details>

so in addition to units, and excluding `software_filters` (which is a string for a list but without clear formatting stated) there is also hplc_recovery_fractions 

```yaml
hplc_recovery_fractions:
  name: hplc_recovery_fractions
  display_name: HPLC recovery fractions
  description: |
    HPLC recovery fractions (the fraction of activity that gets loaded onto the HPLC).
  type: number
  unit: arbitrary
```

which is scalar (I thought that they might be a list ;) ), but especially since a scalar -- we should make them into singular as well IMHO and add to common principles (if not there) that should be singular.
