### ISSUE TITLE
Disambiguate Authors: format is not specified, and not enriched with ORCID

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-2-devel#82]
ATM Authors field is just a list of free form strings. That complicates interlinking bids datasets easily across authors/contributors, as expressed e.g. by @lzehl in their pipeline for inclusion of BIDS datasets within openMINDs KG etc. ATM we have in the  
https://github.com/bids-standard/bids-specification/blob/HEAD/src/schema/objects/metadata.yaml#L207
 we have

```yaml
Authors:
  name: Authors
  display_name: Authors
  description: |
    List of individuals who contributed to the creation/curation of the dataset.
  type: array
  items:
    type: string
```

I feel that we better start defining some notion of a Person which would have clear mapping schema.org's [Person](https://schema.org/Person) record. Critically
- separate first (given) from last (family) name

Ideally, provide additional metadata relevant per person
- ORCID
- Affiliation(s), also in a standardized form

If we solve the critical issue, we could then rely on CITATION.cff to be the one which would provide necessary more structured data (ORCID, affiliations), but need to keep in mind some of already identified shortcomings (which might later be worked out in CITATION.cff):

- https://github.com/citation-file-format/citation-file-format/issues/268

and unfortunately CITATION.cff not really seeing much of "development" in the past year(s).
